/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
import * as import0 from '../../../style/colors.scss.shim.ngstyle';
export var styles = [
    'header[_ngcontent-%COMP%] {\r\n  position: fixed;\r\n  top: 4px;\r\n  left: 0;\r\n  width: 100%;\r\n  height: 60px;\r\n  background-color: $mid-orange;\r\n}\r\nnav[_ngcontent-%COMP%] {\r\n  padding-top: 8px;\r\n  height: 54px;\r\n  background-color: $blue-grey;\r\n}\r\nnav[_ngcontent-%COMP%]   input[_ngcontent-%COMP%]{\r\n  display: inline-block;\r\n  margin-left: 50px;\r\n\r\n}',
    import0.styles
];
//# sourceMappingURL=navbar.component.scss.shim.ngstyle.js.map