/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '../../../style/colors.scss.shim.ngstyle';
export const styles:any[] = [
  'header[_ngcontent-%COMP%] {\r\n  position: fixed;\r\n  top: 4px;\r\n  left: 0;\r\n  width: 100%;\r\n  height: 60px;\r\n  background-color: $mid-orange;\r\n}\r\nnav[_ngcontent-%COMP%] {\r\n  padding-top: 8px;\r\n  height: 54px;\r\n  background-color: $blue-grey;\r\n}\r\nnav[_ngcontent-%COMP%]   input[_ngcontent-%COMP%]{\r\n  display: inline-block;\r\n  margin-left: 50px;\r\n\r\n}',
  import0.styles
]
;
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvYWJvdGV6L0Rlc2t0b3AvdGVzdDIvc3JjL2FwcC9jb21wb25lbnRzL25hdmJhci9uYXZiYXIuY29tcG9uZW50LnNjc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvYWJvdGV6L0Rlc2t0b3AvdGVzdDIvc3JjL2FwcC9jb21wb25lbnRzL25hdmJhci9uYXZiYXIuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7OyJ9
