/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['//[_ngcontent-%COMP%]   component[_ngcontent-%COMP%]   styles[_ngcontent-%COMP%]   are[_ngcontent-%COMP%]   encapsulated[_ngcontent-%COMP%]   and[_ngcontent-%COMP%]   only[_ngcontent-%COMP%]   applied[_ngcontent-%COMP%]   to[_ngcontent-%COMP%]   their[_ngcontent-%COMP%]   components\r\n*[_ngcontent-%COMP%] {\r\n  color: #4286f4;\r\n}'];
//# sourceMappingURL=home.component.scss.shim.ngstyle.js.map