/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['//[_ngcontent-%COMP%]   component[_ngcontent-%COMP%]   styles[_ngcontent-%COMP%]   are[_ngcontent-%COMP%]   encapsulated[_ngcontent-%COMP%]   and[_ngcontent-%COMP%]   only[_ngcontent-%COMP%]   applied[_ngcontent-%COMP%]   to[_ngcontent-%COMP%]   their[_ngcontent-%COMP%]   components\r\n*[_ngcontent-%COMP%] {\r\n  color: #4286f4;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvYWJvdGV6L0Rlc2t0b3AvdGVzdDIvc3JjL2FwcC9jb21wb25lbnRzL2hvbWUvaG9tZS5jb21wb25lbnQuc2Nzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9hYm90ZXovRGVza3RvcC90ZXN0Mi9zcmMvYXBwL2NvbXBvbmVudHMvaG9tZS9ob21lLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
