/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../node_modules/@angular/material/typings/index.ngfactory';
import * as import2 from '@angular/material';
import * as import3 from '@angular/flex-layout/flexbox/api/class';
import * as import4 from '@angular/flex-layout/media-query/media-monitor';
import * as import5 from '../../../../../src/app/components/tabs/tabs.component';
const styles_TabsComponent:any[] = ([] as any[]);
export const RenderType_TabsComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_TabsComponent,
  data: {}
}
);
export function View_TabsComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      (l()(),import0.ɵeld(0,(null as any),(null as any),17,'md-tab-group',[[
        'class',
        'col-md-8 offset-2'
      ]
    ],[
      [
        2,
        'mat-tab-group',
        (null as any)
      ]
      ,
      [
        2,
        'mat-tab-group-dynamic-height',
        (null as any)
      ]
      ,
      [
        2,
        'mat-tab-group-inverted-header',
        (null as any)
      ]

    ]
    ,(null as any),(null as any),import1.View_MdTabGroup_0,import1.RenderType_MdTabGroup)),
    import0.ɵdid(16384,(null as any),0,import2.MdPrefixRejector,[
      [
        2,
        import2.MATERIAL_COMPATIBILITY_MODE
      ]
      ,
      import0.ElementRef
    ]
    ,(null as any),(null as any)),
    import0.ɵdid(10534912,(null as any),1,import2.MdTabGroup,[import0.Renderer2],(null as any),(null as any)),
    import0.ɵqud(603979776,1,{_tabs: 1}),
    import0.ɵdid(933888,(null as any),0,import3.ClassDirective,[
      import4.MediaMonitor,
      import0.IterableDiffers,
      import0.KeyValueDiffers,
      import0.ElementRef,
      import0.Renderer,
      import0.Renderer2
    ]
      ,{classBase: [
        0,
        'classBase'
      ]
    },(null as any)),
    (l()(),import0.ɵted((null as any),['\n  '])),
      (l()(),import0.ɵeld(16777216,(null as any),(null as any),4,'md-tab',[[
        'label',
        'Tab 1'
      ]
    ],(null as any),(null as any),(null as any),import1.View_MdTab_0,import1.RenderType_MdTab)),
    import0.ɵdid(16384,(null as any),0,import2.MdPrefixRejector,[
      [
        2,
        import2.MATERIAL_COMPATIBILITY_MODE
      ]
      ,
      import0.ElementRef
    ]
    ,(null as any),(null as any)),
      import0.ɵdid(114688,[[
        1,
        4
      ]
      ],1,import2.MdTab,[import0.ViewContainerRef],{textLabel: [
        0,
        'textLabel'
      ]
    },(null as any)),
    import0.ɵqud(335544320,2,{templateLabel: 0}),
    (l()(),import0.ɵted(0,['Content 1'])),
    (l()(),import0.ɵted((null as any),['\n  '])),
      (l()(),import0.ɵeld(16777216,(null as any),(null as any),4,'md-tab',[[
        'label',
        'Tab 2'
      ]
    ],(null as any),(null as any),(null as any),import1.View_MdTab_0,import1.RenderType_MdTab)),
    import0.ɵdid(16384,(null as any),0,import2.MdPrefixRejector,[
      [
        2,
        import2.MATERIAL_COMPATIBILITY_MODE
      ]
      ,
      import0.ElementRef
    ]
    ,(null as any),(null as any)),
      import0.ɵdid(114688,[[
        1,
        4
      ]
      ],1,import2.MdTab,[import0.ViewContainerRef],{textLabel: [
        0,
        'textLabel'
      ]
    },(null as any)),
    import0.ɵqud(335544320,3,{templateLabel: 0}),
    (l()(),import0.ɵted(0,['Content 2'])),
    (l()(),import0.ɵted((null as any),['\n'])),
    (l()(),import0.ɵted((null as any),['\n']))
  ]
  ,(ck,v) => {
    const currVal_3:any = 'col-md-8 offset-2';
    ck(v,4,0,currVal_3);
    const currVal_4:any = 'Tab 1';
    ck(v,8,0,currVal_4);
    const currVal_5:any = 'Tab 2';
    ck(v,14,0,currVal_5);
  },(ck,v) => {
    const currVal_0:any = true;
    const currVal_1:any = import0.ɵnov(v,2).dynamicHeight;
    const currVal_2:any = (import0.ɵnov(v,2).headerPosition === 'below');
    ck(v,0,0,currVal_0,currVal_1,currVal_2);
  });
}
function View_TabsComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'my-tabs',([] as any[]),(null as any),(null as any),(null as any),View_TabsComponent_0,RenderType_TabsComponent)),
    import0.ɵdid(49152,(null as any),0,import5.TabsComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const TabsComponentNgFactory:import0.ComponentFactory<import5.TabsComponent> = import0.ɵccf('my-tabs',import5.TabsComponent,View_TabsComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvYWJvdGV6L0Rlc2t0b3AvdGVzdDIvc3JjL2FwcC9jb21wb25lbnRzL3RhYnMvdGFicy5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvYWJvdGV6L0Rlc2t0b3AvdGVzdDIvc3JjL2FwcC9jb21wb25lbnRzL3RhYnMvdGFicy5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9hYm90ZXovRGVza3RvcC90ZXN0Mi9zcmMvYXBwL2NvbXBvbmVudHMvdGFicy90YWJzLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvYWJvdGV6L0Rlc2t0b3AvdGVzdDIvc3JjL2FwcC9jb21wb25lbnRzL3RhYnMvdGFicy5jb21wb25lbnQudHMuVGFic0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxtZC10YWItZ3JvdXAgY2xhc3M9XCJjb2wtbWQtOCBvZmZzZXQtMlwiPlxyXG4gIDxtZC10YWIgbGFiZWw9XCJUYWIgMVwiPkNvbnRlbnQgMTwvbWQtdGFiPlxyXG4gIDxtZC10YWIgbGFiZWw9XCJUYWIgMlwiPkNvbnRlbnQgMjwvbWQtdGFiPlxyXG48L21kLXRhYi1ncm91cD5cclxuIiwiPG15LXRhYnM+PC9teS10YWJzPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O01DQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtNQUFBO1FBQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7UUFBQTtNQUFBOztJQUFBO0tBQUE7Z0JBQUE7TUFBQTtRQUFBOztNQUFBOzs7SUFBQTtLQUFBO2dCQUFBO2dCQUFBO2dCQUFBOzs7Ozs7O0lBQUE7T0FBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQXdDO01BQ3RDO1FBQUE7UUFBQTtNQUFBO0lBQUE7Z0JBQUE7TUFBQTtRQUFBOztNQUFBOzs7SUFBQTtLQUFBO2tCQUFBO1FBQUE7UUFBQTtNQUFBO01BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtnQkFBQTtJQUFzQjtJQUFrQjtNQUN4QztRQUFBO1FBQUE7TUFBQTtJQUFBO2dCQUFBO01BQUE7UUFBQTs7TUFBQTs7O0lBQUE7S0FBQTtrQkFBQTtRQUFBO1FBQUE7TUFBQTtNQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7Z0JBQUE7SUFBc0I7SUFBa0I7SUFDM0I7OztJQUhEO0lBQWQsU0FBYyxTQUFkO0lBQ1U7SUFBUixTQUFRLFNBQVI7SUFDUTtJQUFSLFVBQVEsU0FBUjs7SUFGRjtJQUFBO0lBQUE7SUFBQSxTQUFBLDZCQUFBOzs7OztJQ0FBO2dCQUFBOzs7OyJ9
