/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './app.component.scss.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from './components/navbar/navbar.component.ngfactory';
import * as import3 from './components/navbar/navbar.component';
import * as import4 from '@angular/router';
import * as import5 from './app.component';
import * as import6 from './services/api.service';
const styles_AppComponent:any[] = [import0.styles];
export const RenderType_AppComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_AppComponent,
  data: {}
}
);
export function View_AppComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'my-navbar',([] as any[]),(null as any),(null as any),(null as any),import2.View_NavbarComponent_0,import2.RenderType_NavbarComponent)),
    import1.ɵdid(114688,(null as any),0,import3.NavbarComponent,([] as any[]),(null as any),(null as any)),
    (l()(),import1.ɵted((null as any),['\n'])),
    (l()(),import1.ɵeld(0,(null as any),(null as any),10,'main',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n  '])),
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),[
      'Hello ',
      '!'
    ]
    )),
    (l()(),import1.ɵted((null as any),['\n\n  '])),
    (l()(),import1.ɵted((null as any),['\n  '])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),0,'img',[[
        'src',
        '/img/avaya.jpg'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n\n  '])),
    (l()(),import1.ɵeld(16777216,(null as any),(null as any),1,'router-outlet',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    import1.ɵdid(147456,(null as any),0,import4.RouterOutlet,[
      import4.RouterOutletMap,
      import1.ViewContainerRef,
      import1.ComponentFactoryResolver,
      [
        8,
        (null as any)
      ]

    ]
    ,(null as any),(null as any)),
    (l()(),import1.ɵted((null as any),['\n'])),
    (l()(),import1.ɵted((null as any),['\n'])),
    (l()(),import1.ɵeld(0,(null as any),(null as any),4,'footer',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n  '])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),1,'a',([] as any[]),[[
        8,
        'href',
        4
      ]
    ],(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['Footer'])),
    (l()(),import1.ɵted((null as any),['\n'])),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(ck,v) => {
    var co:import5.AppComponent = v.component;
    const currVal_0:any = co.title;
    ck(v,6,0,currVal_0);
    const currVal_1:any = co.url;
    ck(v,17,0,currVal_1);
  });
}
function View_AppComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'my-app',([] as any[]),(null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
    import1.ɵdid(49152,(null as any),0,import5.AppComponent,[import6.ApiService],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const AppComponentNgFactory:import1.ComponentFactory<import5.AppComponent> = import1.ɵccf('my-app',import5.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvYWJvdGV6L0Rlc2t0b3AvdGVzdDIvc3JjL2FwcC9hcHAuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL2Fib3Rlei9EZXNrdG9wL3Rlc3QyL3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL2Fib3Rlei9EZXNrdG9wL3Rlc3QyL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvYWJvdGV6L0Rlc2t0b3AvdGVzdDIvc3JjL2FwcC9hcHAuY29tcG9uZW50LnRzLkFwcENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxteS1uYXZiYXI+PC9teS1uYXZiYXI+XHJcbjxtYWluPlxyXG4gIDxoMT5IZWxsbyB7e3RpdGxlfX0hPC9oMT5cclxuXHJcbiAgPCEtLSBJbWFnZXMgKGFuZCBhc3NldHMpIGFyZSBwYXJzZWQgYW5kIGxvYWRlZCBmcm9tIHdpdGhpbiB0aGUgcHVibGljIGRpcmVjdG9yeSAtLT5cclxuICA8aW1nIHNyYz1cIi9pbWcvYXZheWEuanBnXCI+XHJcblxyXG4gIDxyb3V0ZXItb3V0bGV0Pjwvcm91dGVyLW91dGxldD5cclxuPC9tYWluPlxyXG48Zm9vdGVyPlxyXG4gIDxhIFtocmVmXT1cInVybFwiPkZvb3RlcjwvYT5cclxuPC9mb290ZXI+XHJcbiIsIjxteS1hcHA+PC9teS1hcHA+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7Z0JBQUE7SUFBdUI7SUFDdkI7SUFBTTtJQUNKO0lBQUk7TUFBQTtNQUFBO0lBQUE7SUFBQTtJQUFxQjtJQUUwRDtNQUNuRjtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQTBCO0lBRTFCO2dCQUFBOzs7O01BQUE7UUFBQTtRQUFBO01BQUE7O0lBQUE7S0FBQTtJQUErQjtJQUMxQjtJQUNQO0lBQVE7TUFDTjtRQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBZ0I7SUFBVTtJQUNuQjs7O0lBWFQ7OztJQUVNO0lBQUE7SUFRRDtJQUFILFVBQUcsU0FBSDs7Ozs7SUNWRjtnQkFBQTs7OzsifQ==
