/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
import * as import0 from '../style/colors.scss.shim.ngstyle';
export var styles = [
    '//   styles   applied   on   [_nghost-%COMP%]   are[_ngcontent-%COMP%]   applied[_ngcontent-%COMP%]   on[_ngcontent-%COMP%]   the[_ngcontent-%COMP%]   current[_ngcontent-%COMP%]   component[_ngcontent-%COMP%], "app"   in   this   case\r\n\r\n[_nghost-%COMP%] {\r\n  display: block;\r\n}\r\n\r\nmain[_ngcontent-%COMP%] {\r\n  padding: 1em;\r\n  font-family: Arial, Helvetica, sans-serif;\r\n  text-align: center;\r\n  margin-top: 50px;\r\n  display: block;\r\n}\r\n\r\nfooter[_ngcontent-%COMP%] {\r\n  text-align: center;\r\n  font-size: 0.8em;\r\n}',
    import0.styles
];
//# sourceMappingURL=app.component.scss.shim.ngstyle.js.map