/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/app/app.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/router';
import * as import4 from '@angular/platform-browser';
import * as import5 from '@angular/http';
import * as import6 from '@angular/forms';
import * as import7 from 'angular-in-memory-web-api/in-memory-web-api.module';
import * as import8 from '@angular/platform-browser/animations';
import * as import9 from '@angular/material';
import * as import10 from '@angular/flex-layout/media-query/_module';
import * as import11 from '@angular/flex-layout/flexbox/_module';
import * as import12 from '../../../src/app/services/in-memory-data.service';
import * as import13 from '@angular/flex-layout/media-query/breakpoints/break-point-registry';
import * as import14 from '@angular/flex-layout/media-query/match-media';
import * as import15 from '../../../src/app/services/api.service';
import * as import16 from '../../node_modules/@angular/material/typings/index.ngfactory';
import * as import17 from './components/home/home.component.ngfactory';
import * as import18 from './components/about/about.component.ngfactory';
import * as import19 from './app.component.ngfactory';
import * as import20 from '@angular/flex-layout/media-query/breakpoints/break-points-provider';
import * as import21 from '@angular/flex-layout/media-query/media-monitor-provider';
import * as import22 from '@angular/flex-layout/media-query/media-monitor';
import * as import23 from '@angular/flex-layout/media-query/observable-media-provider';
import * as import24 from '@angular/flex-layout/media-query/observable-media';
import * as import25 from '../../../src/app/components/home/home.component';
import * as import26 from '../../../src/app/components/about/about.component';
import * as import27 from '@angular/animations/browser';
import * as import28 from 'angular-in-memory-web-api/in-memory-backend.service';
import * as import29 from '@angular/flex-layout/media-query/breakpoints/break-points-token';
class AppModuleInjector extends import0.ɵNgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ErrorHandler_1:any;
  _NgProbeToken_2:any[];
  _ɵg_3:import3.ɵg;
  _APP_INITIALIZER_4:any[];
  _ApplicationInitStatus_5:import0.ApplicationInitStatus;
  _ɵf_6:import0.ɵf;
  _ApplicationRef_7:any;
  _ApplicationModule_8:import0.ApplicationModule;
  _BrowserModule_9:import4.BrowserModule;
  _HttpModule_10:import5.HttpModule;
  _ɵba_11:import6.ɵba;
  _FormsModule_12:import6.FormsModule;
  _ReactiveFormsModule_13:import6.ReactiveFormsModule;
  _ɵa_14:any;
  _UrlSerializer_15:import3.DefaultUrlSerializer;
  _RouterOutletMap_16:import3.RouterOutletMap;
  _ROUTER_CONFIGURATION_17:any;
  _LocationStrategy_18:any;
  _Location_19:import2.Location;
  _Compiler_20:import0.Compiler;
  _NgModuleFactoryLoader_21:import0.SystemJsNgModuleLoader;
  _ROUTES_22:any[];
  _Router_23:any;
  _RouterModule_24:import3.RouterModule;
  _InMemoryWebApiModule_25:import7.InMemoryWebApiModule;
  _BrowserAnimationsModule_26:import8.BrowserAnimationsModule;
  _MATERIAL_SANITY_CHECKS_27:any;
  _CompatibilityModule_28:import9.CompatibilityModule;
  _MdCommonModule_29:import9.MdCommonModule;
  _PlatformModule_30:import9.PlatformModule;
  _ScrollDispatchModule_31:import9.ScrollDispatchModule;
  _MdRippleModule_32:import9.MdRippleModule;
  _MdSelectionModule_33:import9.MdSelectionModule;
  _MdOptionModule_34:import9.MdOptionModule;
  _PortalModule_35:import9.PortalModule;
  _OverlayModule_36:import9.OverlayModule;
  _MdAutocompleteModule_37:import9.MdAutocompleteModule;
  _StyleModule_38:import9.StyleModule;
  _MdButtonModule_39:import9.MdButtonModule;
  _MdButtonToggleModule_40:import9.MdButtonToggleModule;
  _MdCardModule_41:import9.MdCardModule;
  _MdChipsModule_42:import9.MdChipsModule;
  _MdCheckboxModule_43:import9.MdCheckboxModule;
  _A11yModule_44:import9.A11yModule;
  _MdDialogModule_45:import9.MdDialogModule;
  _MdDatepickerModule_46:import9.MdDatepickerModule;
  _MdLineModule_47:import9.MdLineModule;
  _MdGridListModule_48:import9.MdGridListModule;
  _MdIconModule_49:import9.MdIconModule;
  _MdInputModule_50:import9.MdInputModule;
  _MdListModule_51:import9.MdListModule;
  _MdMenuModule_52:import9.MdMenuModule;
  _MdProgressBarModule_53:import9.MdProgressBarModule;
  _MdProgressSpinnerModule_54:import9.MdProgressSpinnerModule;
  _MdRadioModule_55:import9.MdRadioModule;
  _MdSelectModule_56:import9.MdSelectModule;
  _MdSidenavModule_57:import9.MdSidenavModule;
  _RtlModule_58:import9.RtlModule;
  _MdSliderModule_59:import9.MdSliderModule;
  _MdSlideToggleModule_60:import9.MdSlideToggleModule;
  _MdSnackBarModule_61:import9.MdSnackBarModule;
  _ObserveContentModule_62:import9.ObserveContentModule;
  _MdTabsModule_63:import9.MdTabsModule;
  _MdToolbarModule_64:import9.MdToolbarModule;
  _MdTooltipModule_65:import9.MdTooltipModule;
  _MaterialModule_66:import9.MaterialModule;
  _MediaQueriesModule_67:import10.MediaQueriesModule;
  _FlexLayoutModule_68:import11.FlexLayoutModule;
  _AppModule_69:import1.AppModule;
  __LOCALE_ID_70:any;
  __NgLocalization_71:import2.NgLocaleLocalization;
  __APP_ID_72:any;
  __IterableDiffers_73:any;
  __KeyValueDiffers_74:any;
  __DomSanitizer_75:import4.ɵe;
  __Sanitizer_76:any;
  __HAMMER_GESTURE_CONFIG_77:import9.GestureConfig;
  __EVENT_MANAGER_PLUGINS_78:any[];
  __EventManager_79:import4.EventManager;
  __ɵDomSharedStylesHost_80:import4.ɵDomSharedStylesHost;
  __ɵDomRendererFactory2_81:import4.ɵDomRendererFactory2;
  __AnimationDriver_82:any;
  __ɵAnimationStyleNormalizer_83:any;
  __ɵAnimationEngine_84:import8.ɵa;
  __RendererFactory2_85:any;
  __ɵSharedStylesHost_86:any;
  __Testability_87:import0.Testability;
  __Meta_88:import4.Meta;
  __Title_89:import4.Title;
  __InMemoryDbService_90:import12.UserData;
  _InMemoryBackendConfig_91:any;
  __XHRBackend_92:any;
  __RequestOptions_93:import5.BaseRequestOptions;
  __Http_94:any;
  __BrowserXhr_95:import5.BrowserXhr;
  __ResponseOptions_96:import5.BaseResponseOptions;
  __XSRFStrategy_97:any;
  __ɵi_98:import6.ɵi;
  __FormBuilder_99:import6.FormBuilder;
  __Platform_100:import9.Platform;
  __ScrollDispatcher_101:any;
  __ViewportRuler_102:any;
  __OverlayContainer_103:any;
  __ɵo_104:import9.ɵo;
  __Overlay_105:import9.Overlay;
  __FocusOriginMonitor_106:any;
  __UniqueSelectionDispatcher_107:any;
  __InteractivityChecker_108:import9.InteractivityChecker;
  __FocusTrapFactory_109:import9.FocusTrapFactory;
  __LiveAnnouncer_110:any;
  __MdDialog_111:import9.MdDialog;
  __MdDatepickerIntl_112:import9.MdDatepickerIntl;
  __MdIconRegistry_113:any;
  __MdSnackBar_114:import9.MdSnackBar;
  __ɵa_115:import9.ɵa;
  __BREAKPOINTS_116:any;
  __BreakPointRegistry_117:import13.BreakPointRegistry;
  __MatchMedia_118:import14.MatchMedia;
  __MediaMonitor_119:any;
  __ObservableMedia_120:any;
  __ActivatedRoute_121:any;
  __NoPreloading_122:import3.NoPreloading;
  __PreloadingStrategy_123:any;
  __RouterPreloader_124:import3.RouterPreloader;
  __PreloadAllModules_125:import3.PreloadAllModules;
  __ROUTER_INITIALIZER_126:any;
  __APP_BOOTSTRAP_LISTENER_127:any[];
  __ApiService_128:import15.ApiService;
  constructor(parent:import0.Injector) {
    super(parent,[
      import16.MdDialogContainerNgFactory,
      import16.MdDatepickerContentNgFactory,
      import16.MdSnackBarContainerNgFactory,
      import16.SimpleSnackBarNgFactory,
      import16.TooltipComponentNgFactory,
      import17.HomeComponentNgFactory,
      import18.AboutComponentNgFactory,
      import19.AppComponentNgFactory
    ]
    ,[import19.AppComponentNgFactory]);
  }
  get _LOCALE_ID_70():any {
    if ((this.__LOCALE_ID_70 == null)) { (this.__LOCALE_ID_70 = import0.ɵn(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_70;
  }
  get _NgLocalization_71():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_71 == null)) { (this.__NgLocalization_71 = new import2.NgLocaleLocalization(this._LOCALE_ID_70)); }
    return this.__NgLocalization_71;
  }
  get _APP_ID_72():any {
    if ((this.__APP_ID_72 == null)) { (this.__APP_ID_72 = import0.ɵg()); }
    return this.__APP_ID_72;
  }
  get _IterableDiffers_73():any {
    if ((this.__IterableDiffers_73 == null)) { (this.__IterableDiffers_73 = import0.ɵl()); }
    return this.__IterableDiffers_73;
  }
  get _KeyValueDiffers_74():any {
    if ((this.__KeyValueDiffers_74 == null)) { (this.__KeyValueDiffers_74 = import0.ɵm()); }
    return this.__KeyValueDiffers_74;
  }
  get _DomSanitizer_75():import4.ɵe {
    if ((this.__DomSanitizer_75 == null)) { (this.__DomSanitizer_75 = new import4.ɵe(this.parent.get(import4.DOCUMENT))); }
    return this.__DomSanitizer_75;
  }
  get _Sanitizer_76():any {
    if ((this.__Sanitizer_76 == null)) { (this.__Sanitizer_76 = this._DomSanitizer_75); }
    return this.__Sanitizer_76;
  }
  get _HAMMER_GESTURE_CONFIG_77():import9.GestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_77 == null)) { (this.__HAMMER_GESTURE_CONFIG_77 = new import9.GestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_77;
  }
  get _EVENT_MANAGER_PLUGINS_78():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_78 == null)) { (this.__EVENT_MANAGER_PLUGINS_78 = [
      new import4.ɵDomEventsPlugin(this.parent.get(import4.DOCUMENT)),
      new import4.ɵKeyEventsPlugin(this.parent.get(import4.DOCUMENT)),
      new import4.ɵHammerGesturesPlugin(this.parent.get(import4.DOCUMENT),this._HAMMER_GESTURE_CONFIG_77)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_78;
  }
  get _EventManager_79():import4.EventManager {
    if ((this.__EventManager_79 == null)) { (this.__EventManager_79 = new import4.EventManager(this._EVENT_MANAGER_PLUGINS_78,this.parent.get(import0.NgZone))); }
    return this.__EventManager_79;
  }
  get _ɵDomSharedStylesHost_80():import4.ɵDomSharedStylesHost {
    if ((this.__ɵDomSharedStylesHost_80 == null)) { (this.__ɵDomSharedStylesHost_80 = new import4.ɵDomSharedStylesHost(this.parent.get(import4.DOCUMENT))); }
    return this.__ɵDomSharedStylesHost_80;
  }
  get _ɵDomRendererFactory2_81():import4.ɵDomRendererFactory2 {
    if ((this.__ɵDomRendererFactory2_81 == null)) { (this.__ɵDomRendererFactory2_81 = new import4.ɵDomRendererFactory2(this._EventManager_79,this._ɵDomSharedStylesHost_80)); }
    return this.__ɵDomRendererFactory2_81;
  }
  get _AnimationDriver_82():any {
    if ((this.__AnimationDriver_82 == null)) { (this.__AnimationDriver_82 = import8.ɵb()); }
    return this.__AnimationDriver_82;
  }
  get _ɵAnimationStyleNormalizer_83():any {
    if ((this.__ɵAnimationStyleNormalizer_83 == null)) { (this.__ɵAnimationStyleNormalizer_83 = import8.ɵc()); }
    return this.__ɵAnimationStyleNormalizer_83;
  }
  get _ɵAnimationEngine_84():import8.ɵa {
    if ((this.__ɵAnimationEngine_84 == null)) { (this.__ɵAnimationEngine_84 = new import8.ɵa(this._AnimationDriver_82,this._ɵAnimationStyleNormalizer_83)); }
    return this.__ɵAnimationEngine_84;
  }
  get _RendererFactory2_85():any {
    if ((this.__RendererFactory2_85 == null)) { (this.__RendererFactory2_85 = import8.ɵd(this._ɵDomRendererFactory2_81,this._ɵAnimationEngine_84,this.parent.get(import0.NgZone))); }
    return this.__RendererFactory2_85;
  }
  get _ɵSharedStylesHost_86():any {
    if ((this.__ɵSharedStylesHost_86 == null)) { (this.__ɵSharedStylesHost_86 = this._ɵDomSharedStylesHost_80); }
    return this.__ɵSharedStylesHost_86;
  }
  get _Testability_87():import0.Testability {
    if ((this.__Testability_87 == null)) { (this.__Testability_87 = new import0.Testability(this.parent.get(import0.NgZone))); }
    return this.__Testability_87;
  }
  get _Meta_88():import4.Meta {
    if ((this.__Meta_88 == null)) { (this.__Meta_88 = new import4.Meta(this.parent.get(import4.DOCUMENT))); }
    return this.__Meta_88;
  }
  get _Title_89():import4.Title {
    if ((this.__Title_89 == null)) { (this.__Title_89 = new import4.Title(this.parent.get(import4.DOCUMENT))); }
    return this.__Title_89;
  }
  get _InMemoryDbService_90():import12.UserData {
    if ((this.__InMemoryDbService_90 == null)) { (this.__InMemoryDbService_90 = new import12.UserData()); }
    return this.__InMemoryDbService_90;
  }
  get _XHRBackend_92():any {
    if ((this.__XHRBackend_92 == null)) { (this.__XHRBackend_92 = import7.inMemoryBackendServiceFactory(this,this._InMemoryDbService_90,this._InMemoryBackendConfig_91)); }
    return this.__XHRBackend_92;
  }
  get _RequestOptions_93():import5.BaseRequestOptions {
    if ((this.__RequestOptions_93 == null)) { (this.__RequestOptions_93 = new import5.BaseRequestOptions()); }
    return this.__RequestOptions_93;
  }
  get _Http_94():any {
    if ((this.__Http_94 == null)) { (this.__Http_94 = import5.ɵc(this._XHRBackend_92,this._RequestOptions_93)); }
    return this.__Http_94;
  }
  get _BrowserXhr_95():import5.BrowserXhr {
    if ((this.__BrowserXhr_95 == null)) { (this.__BrowserXhr_95 = new import5.BrowserXhr()); }
    return this.__BrowserXhr_95;
  }
  get _ResponseOptions_96():import5.BaseResponseOptions {
    if ((this.__ResponseOptions_96 == null)) { (this.__ResponseOptions_96 = new import5.BaseResponseOptions()); }
    return this.__ResponseOptions_96;
  }
  get _XSRFStrategy_97():any {
    if ((this.__XSRFStrategy_97 == null)) { (this.__XSRFStrategy_97 = import5.ɵb()); }
    return this.__XSRFStrategy_97;
  }
  get _ɵi_98():import6.ɵi {
    if ((this.__ɵi_98 == null)) { (this.__ɵi_98 = new import6.ɵi()); }
    return this.__ɵi_98;
  }
  get _FormBuilder_99():import6.FormBuilder {
    if ((this.__FormBuilder_99 == null)) { (this.__FormBuilder_99 = new import6.FormBuilder()); }
    return this.__FormBuilder_99;
  }
  get _Platform_100():import9.Platform {
    if ((this.__Platform_100 == null)) { (this.__Platform_100 = new import9.Platform()); }
    return this.__Platform_100;
  }
  get _ScrollDispatcher_101():any {
    if ((this.__ScrollDispatcher_101 == null)) { (this.__ScrollDispatcher_101 = import9.ɵf(this.parent.get(import9.ScrollDispatcher,(null as any)),this.parent.get(import0.NgZone),this._Platform_100)); }
    return this.__ScrollDispatcher_101;
  }
  get _ViewportRuler_102():any {
    if ((this.__ViewportRuler_102 == null)) { (this.__ViewportRuler_102 = import9.ɵd(this.parent.get(import9.ViewportRuler,(null as any)),this._ScrollDispatcher_101)); }
    return this.__ViewportRuler_102;
  }
  get _OverlayContainer_103():any {
    if ((this.__OverlayContainer_103 == null)) { (this.__OverlayContainer_103 = import9.ɵb(this.parent.get(import9.OverlayContainer,(null as any)))); }
    return this.__OverlayContainer_103;
  }
  get _ɵo_104():import9.ɵo {
    if ((this.__ɵo_104 == null)) { (this.__ɵo_104 = new import9.ɵo(this._ViewportRuler_102)); }
    return this.__ɵo_104;
  }
  get _Overlay_105():import9.Overlay {
    if ((this.__Overlay_105 == null)) { (this.__Overlay_105 = new import9.Overlay(this._OverlayContainer_103,this.componentFactoryResolver,this._ɵo_104,this._ApplicationRef_7,this,this.parent.get(import0.NgZone))); }
    return this.__Overlay_105;
  }
  get _FocusOriginMonitor_106():any {
    if ((this.__FocusOriginMonitor_106 == null)) { (this.__FocusOriginMonitor_106 = import9.FOCUS_ORIGIN_MONITOR_PROVIDER_FACTORY(this.parent.get(import9.FocusOriginMonitor,(null as any)),this.parent.get(import0.NgZone),this._Platform_100)); }
    return this.__FocusOriginMonitor_106;
  }
  get _UniqueSelectionDispatcher_107():any {
    if ((this.__UniqueSelectionDispatcher_107 == null)) { (this.__UniqueSelectionDispatcher_107 = import9.ɵj(this.parent.get(import9.UniqueSelectionDispatcher,(null as any)))); }
    return this.__UniqueSelectionDispatcher_107;
  }
  get _InteractivityChecker_108():import9.InteractivityChecker {
    if ((this.__InteractivityChecker_108 == null)) { (this.__InteractivityChecker_108 = new import9.InteractivityChecker(this._Platform_100)); }
    return this.__InteractivityChecker_108;
  }
  get _FocusTrapFactory_109():import9.FocusTrapFactory {
    if ((this.__FocusTrapFactory_109 == null)) { (this.__FocusTrapFactory_109 = new import9.FocusTrapFactory(this._InteractivityChecker_108,this.parent.get(import0.NgZone))); }
    return this.__FocusTrapFactory_109;
  }
  get _LiveAnnouncer_110():any {
    if ((this.__LiveAnnouncer_110 == null)) { (this.__LiveAnnouncer_110 = import9.ɵi(this.parent.get(import9.LiveAnnouncer,(null as any)),this.parent.get(import9.LIVE_ANNOUNCER_ELEMENT_TOKEN,(null as any)),this._Platform_100)); }
    return this.__LiveAnnouncer_110;
  }
  get _MdDialog_111():import9.MdDialog {
    if ((this.__MdDialog_111 == null)) { (this.__MdDialog_111 = new import9.MdDialog(this._Overlay_105,this,this._ViewportRuler_102,this._Location_19,this.parent.get(import9.MdDialog,(null as any)))); }
    return this.__MdDialog_111;
  }
  get _MdDatepickerIntl_112():import9.MdDatepickerIntl {
    if ((this.__MdDatepickerIntl_112 == null)) { (this.__MdDatepickerIntl_112 = new import9.MdDatepickerIntl()); }
    return this.__MdDatepickerIntl_112;
  }
  get _MdIconRegistry_113():any {
    if ((this.__MdIconRegistry_113 == null)) { (this.__MdIconRegistry_113 = import9.ICON_REGISTRY_PROVIDER_FACTORY(this.parent.get(import9.MdIconRegistry,(null as any)),this._Http_94,this._DomSanitizer_75)); }
    return this.__MdIconRegistry_113;
  }
  get _MdSnackBar_114():import9.MdSnackBar {
    if ((this.__MdSnackBar_114 == null)) { (this.__MdSnackBar_114 = new import9.MdSnackBar(this._Overlay_105,this._LiveAnnouncer_110,this.parent.get(import9.MdSnackBar,(null as any)))); }
    return this.__MdSnackBar_114;
  }
  get _ɵa_115():import9.ɵa {
    if ((this.__ɵa_115 == null)) { (this.__ɵa_115 = new import9.ɵa()); }
    return this.__ɵa_115;
  }
  get _BREAKPOINTS_116():any {
    if ((this.__BREAKPOINTS_116 == null)) { (this.__BREAKPOINTS_116 = import20.DEFAULT_BREAKPOINTS_PROVIDER_FACTORY()); }
    return this.__BREAKPOINTS_116;
  }
  get _BreakPointRegistry_117():import13.BreakPointRegistry {
    if ((this.__BreakPointRegistry_117 == null)) { (this.__BreakPointRegistry_117 = new import13.BreakPointRegistry(this._BREAKPOINTS_116)); }
    return this.__BreakPointRegistry_117;
  }
  get _MatchMedia_118():import14.MatchMedia {
    if ((this.__MatchMedia_118 == null)) { (this.__MatchMedia_118 = new import14.MatchMedia(this.parent.get(import0.NgZone))); }
    return this.__MatchMedia_118;
  }
  get _MediaMonitor_119():any {
    if ((this.__MediaMonitor_119 == null)) { (this.__MediaMonitor_119 = import21.MEDIA_MONITOR_PROVIDER_FACTORY(this.parent.get(import22.MediaMonitor,(null as any)),this._BreakPointRegistry_117,this._MatchMedia_118)); }
    return this.__MediaMonitor_119;
  }
  get _ObservableMedia_120():any {
    if ((this.__ObservableMedia_120 == null)) { (this.__ObservableMedia_120 = import23.OBSERVABLE_MEDIA_PROVIDER_FACTORY(this.parent.get(import24.ObservableMedia,(null as any)),this._MatchMedia_118,this._BreakPointRegistry_117)); }
    return this.__ObservableMedia_120;
  }
  get _ActivatedRoute_121():any {
    if ((this.__ActivatedRoute_121 == null)) { (this.__ActivatedRoute_121 = import3.ɵf(this._Router_23)); }
    return this.__ActivatedRoute_121;
  }
  get _NoPreloading_122():import3.NoPreloading {
    if ((this.__NoPreloading_122 == null)) { (this.__NoPreloading_122 = new import3.NoPreloading()); }
    return this.__NoPreloading_122;
  }
  get _PreloadingStrategy_123():any {
    if ((this.__PreloadingStrategy_123 == null)) { (this.__PreloadingStrategy_123 = this._NoPreloading_122); }
    return this.__PreloadingStrategy_123;
  }
  get _RouterPreloader_124():import3.RouterPreloader {
    if ((this.__RouterPreloader_124 == null)) { (this.__RouterPreloader_124 = new import3.RouterPreloader(this._Router_23,this._NgModuleFactoryLoader_21,this._Compiler_20,this,this._PreloadingStrategy_123)); }
    return this.__RouterPreloader_124;
  }
  get _PreloadAllModules_125():import3.PreloadAllModules {
    if ((this.__PreloadAllModules_125 == null)) { (this.__PreloadAllModules_125 = new import3.PreloadAllModules()); }
    return this.__PreloadAllModules_125;
  }
  get _ROUTER_INITIALIZER_126():any {
    if ((this.__ROUTER_INITIALIZER_126 == null)) { (this.__ROUTER_INITIALIZER_126 = import3.ɵi(this._ɵg_3)); }
    return this.__ROUTER_INITIALIZER_126;
  }
  get _APP_BOOTSTRAP_LISTENER_127():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_127 == null)) { (this.__APP_BOOTSTRAP_LISTENER_127 = [this._ROUTER_INITIALIZER_126]); }
    return this.__APP_BOOTSTRAP_LISTENER_127;
  }
  get _ApiService_128():import15.ApiService {
    if ((this.__ApiService_128 == null)) { (this.__ApiService_128 = new import15.ApiService(this._Http_94)); }
    return this.__ApiService_128;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ErrorHandler_1 = import4.ɵa();
    this._NgProbeToken_2 = [import3.ɵb()];
    this._ɵg_3 = new import3.ɵg(this);
    this._APP_INITIALIZER_4 = [
      import0.ɵo,
      import4.ɵc(this.parent.get(import4.NgProbeToken,(null as any)),this._NgProbeToken_2),
      import3.ɵh(this._ɵg_3)
    ]
    ;
    this._ApplicationInitStatus_5 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_4);
    this._ɵf_6 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_1,this.componentFactoryResolver,this._ApplicationInitStatus_5);
    this._ApplicationRef_7 = this._ɵf_6;
    this._ApplicationModule_8 = new import0.ApplicationModule(this._ApplicationRef_7);
    this._BrowserModule_9 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._HttpModule_10 = new import5.HttpModule();
    this._ɵba_11 = new import6.ɵba();
    this._FormsModule_12 = new import6.FormsModule();
    this._ReactiveFormsModule_13 = new import6.ReactiveFormsModule();
    this._ɵa_14 = import3.ɵd(this.parent.get(import3.Router,(null as any)));
    this._UrlSerializer_15 = new import3.DefaultUrlSerializer();
    this._RouterOutletMap_16 = new import3.RouterOutletMap();
    this._ROUTER_CONFIGURATION_17 = {};
    this._LocationStrategy_18 = import3.ɵc(this.parent.get(import2.PlatformLocation),this.parent.get(import2.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_17);
    this._Location_19 = new import2.Location(this._LocationStrategy_18);
    this._Compiler_20 = new import0.Compiler();
    this._NgModuleFactoryLoader_21 = new import0.SystemJsNgModuleLoader(this._Compiler_20,this.parent.get(import0.SystemJsNgModuleLoaderConfig,(null as any)));
      this._ROUTES_22 = [[
        {
          path: '',
          component: import25.HomeComponent
        }
        ,
        {
          path: 'about',
          component: import26.AboutComponent
        }

      ]
    ];
    this._Router_23 = import3.ɵe(this._ApplicationRef_7,this._UrlSerializer_15,this._RouterOutletMap_16,this._Location_19,this,this._NgModuleFactoryLoader_21,this._Compiler_20,this._ROUTES_22,this._ROUTER_CONFIGURATION_17,this.parent.get(import3.UrlHandlingStrategy,(null as any)),this.parent.get(import3.RouteReuseStrategy,(null as any)));
    this._RouterModule_24 = new import3.RouterModule(this._ɵa_14,this._Router_23);
    this._InMemoryWebApiModule_25 = new import7.InMemoryWebApiModule();
    this._BrowserAnimationsModule_26 = new import8.BrowserAnimationsModule();
    this._MATERIAL_SANITY_CHECKS_27 = true;
    this._CompatibilityModule_28 = new import9.CompatibilityModule(this.parent.get(import4.DOCUMENT,(null as any)),this._MATERIAL_SANITY_CHECKS_27);
    this._MdCommonModule_29 = new import9.MdCommonModule();
    this._PlatformModule_30 = new import9.PlatformModule();
    this._ScrollDispatchModule_31 = new import9.ScrollDispatchModule();
    this._MdRippleModule_32 = new import9.MdRippleModule();
    this._MdSelectionModule_33 = new import9.MdSelectionModule();
    this._MdOptionModule_34 = new import9.MdOptionModule();
    this._PortalModule_35 = new import9.PortalModule();
    this._OverlayModule_36 = new import9.OverlayModule();
    this._MdAutocompleteModule_37 = new import9.MdAutocompleteModule();
    this._StyleModule_38 = new import9.StyleModule();
    this._MdButtonModule_39 = new import9.MdButtonModule();
    this._MdButtonToggleModule_40 = new import9.MdButtonToggleModule();
    this._MdCardModule_41 = new import9.MdCardModule();
    this._MdChipsModule_42 = new import9.MdChipsModule();
    this._MdCheckboxModule_43 = new import9.MdCheckboxModule();
    this._A11yModule_44 = new import9.A11yModule();
    this._MdDialogModule_45 = new import9.MdDialogModule();
    this._MdDatepickerModule_46 = new import9.MdDatepickerModule();
    this._MdLineModule_47 = new import9.MdLineModule();
    this._MdGridListModule_48 = new import9.MdGridListModule();
    this._MdIconModule_49 = new import9.MdIconModule();
    this._MdInputModule_50 = new import9.MdInputModule();
    this._MdListModule_51 = new import9.MdListModule();
    this._MdMenuModule_52 = new import9.MdMenuModule();
    this._MdProgressBarModule_53 = new import9.MdProgressBarModule();
    this._MdProgressSpinnerModule_54 = new import9.MdProgressSpinnerModule();
    this._MdRadioModule_55 = new import9.MdRadioModule();
    this._MdSelectModule_56 = new import9.MdSelectModule();
    this._MdSidenavModule_57 = new import9.MdSidenavModule();
    this._RtlModule_58 = new import9.RtlModule();
    this._MdSliderModule_59 = new import9.MdSliderModule();
    this._MdSlideToggleModule_60 = new import9.MdSlideToggleModule();
    this._MdSnackBarModule_61 = new import9.MdSnackBarModule();
    this._ObserveContentModule_62 = new import9.ObserveContentModule();
    this._MdTabsModule_63 = new import9.MdTabsModule();
    this._MdToolbarModule_64 = new import9.MdToolbarModule();
    this._MdTooltipModule_65 = new import9.MdTooltipModule();
    this._MaterialModule_66 = new import9.MaterialModule();
    this._MediaQueriesModule_67 = new import10.MediaQueriesModule();
    this._FlexLayoutModule_68 = new import11.FlexLayoutModule();
    this._AppModule_69 = new import1.AppModule(this._ApplicationRef_7);
    this._InMemoryBackendConfig_91 = (undefined as any);
    return this._AppModule_69;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_1; }
    if ((token === import0.NgProbeToken)) { return this._NgProbeToken_2; }
    if ((token === import3.ɵg)) { return this._ɵg_3; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_4; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_5; }
    if ((token === import0.ɵf)) { return this._ɵf_6; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_7; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_8; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_9; }
    if ((token === import5.HttpModule)) { return this._HttpModule_10; }
    if ((token === import6.ɵba)) { return this._ɵba_11; }
    if ((token === import6.FormsModule)) { return this._FormsModule_12; }
    if ((token === import6.ReactiveFormsModule)) { return this._ReactiveFormsModule_13; }
    if ((token === import3.ɵa)) { return this._ɵa_14; }
    if ((token === import3.UrlSerializer)) { return this._UrlSerializer_15; }
    if ((token === import3.RouterOutletMap)) { return this._RouterOutletMap_16; }
    if ((token === import3.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_17; }
    if ((token === import2.LocationStrategy)) { return this._LocationStrategy_18; }
    if ((token === import2.Location)) { return this._Location_19; }
    if ((token === import0.Compiler)) { return this._Compiler_20; }
    if ((token === import0.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_21; }
    if ((token === import3.ROUTES)) { return this._ROUTES_22; }
    if ((token === import3.Router)) { return this._Router_23; }
    if ((token === import3.RouterModule)) { return this._RouterModule_24; }
    if ((token === import7.InMemoryWebApiModule)) { return this._InMemoryWebApiModule_25; }
    if ((token === import8.BrowserAnimationsModule)) { return this._BrowserAnimationsModule_26; }
    if ((token === import9.MATERIAL_SANITY_CHECKS)) { return this._MATERIAL_SANITY_CHECKS_27; }
    if ((token === import9.CompatibilityModule)) { return this._CompatibilityModule_28; }
    if ((token === import9.MdCommonModule)) { return this._MdCommonModule_29; }
    if ((token === import9.PlatformModule)) { return this._PlatformModule_30; }
    if ((token === import9.ScrollDispatchModule)) { return this._ScrollDispatchModule_31; }
    if ((token === import9.MdRippleModule)) { return this._MdRippleModule_32; }
    if ((token === import9.MdSelectionModule)) { return this._MdSelectionModule_33; }
    if ((token === import9.MdOptionModule)) { return this._MdOptionModule_34; }
    if ((token === import9.PortalModule)) { return this._PortalModule_35; }
    if ((token === import9.OverlayModule)) { return this._OverlayModule_36; }
    if ((token === import9.MdAutocompleteModule)) { return this._MdAutocompleteModule_37; }
    if ((token === import9.StyleModule)) { return this._StyleModule_38; }
    if ((token === import9.MdButtonModule)) { return this._MdButtonModule_39; }
    if ((token === import9.MdButtonToggleModule)) { return this._MdButtonToggleModule_40; }
    if ((token === import9.MdCardModule)) { return this._MdCardModule_41; }
    if ((token === import9.MdChipsModule)) { return this._MdChipsModule_42; }
    if ((token === import9.MdCheckboxModule)) { return this._MdCheckboxModule_43; }
    if ((token === import9.A11yModule)) { return this._A11yModule_44; }
    if ((token === import9.MdDialogModule)) { return this._MdDialogModule_45; }
    if ((token === import9.MdDatepickerModule)) { return this._MdDatepickerModule_46; }
    if ((token === import9.MdLineModule)) { return this._MdLineModule_47; }
    if ((token === import9.MdGridListModule)) { return this._MdGridListModule_48; }
    if ((token === import9.MdIconModule)) { return this._MdIconModule_49; }
    if ((token === import9.MdInputModule)) { return this._MdInputModule_50; }
    if ((token === import9.MdListModule)) { return this._MdListModule_51; }
    if ((token === import9.MdMenuModule)) { return this._MdMenuModule_52; }
    if ((token === import9.MdProgressBarModule)) { return this._MdProgressBarModule_53; }
    if ((token === import9.MdProgressSpinnerModule)) { return this._MdProgressSpinnerModule_54; }
    if ((token === import9.MdRadioModule)) { return this._MdRadioModule_55; }
    if ((token === import9.MdSelectModule)) { return this._MdSelectModule_56; }
    if ((token === import9.MdSidenavModule)) { return this._MdSidenavModule_57; }
    if ((token === import9.RtlModule)) { return this._RtlModule_58; }
    if ((token === import9.MdSliderModule)) { return this._MdSliderModule_59; }
    if ((token === import9.MdSlideToggleModule)) { return this._MdSlideToggleModule_60; }
    if ((token === import9.MdSnackBarModule)) { return this._MdSnackBarModule_61; }
    if ((token === import9.ObserveContentModule)) { return this._ObserveContentModule_62; }
    if ((token === import9.MdTabsModule)) { return this._MdTabsModule_63; }
    if ((token === import9.MdToolbarModule)) { return this._MdToolbarModule_64; }
    if ((token === import9.MdTooltipModule)) { return this._MdTooltipModule_65; }
    if ((token === import9.MaterialModule)) { return this._MaterialModule_66; }
    if ((token === import10.MediaQueriesModule)) { return this._MediaQueriesModule_67; }
    if ((token === import11.FlexLayoutModule)) { return this._FlexLayoutModule_68; }
    if ((token === import1.AppModule)) { return this._AppModule_69; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_70; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_71; }
    if ((token === import0.APP_ID)) { return this._APP_ID_72; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_73; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_74; }
    if ((token === import4.DomSanitizer)) { return this._DomSanitizer_75; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_76; }
    if ((token === import4.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_77; }
    if ((token === import4.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_78; }
    if ((token === import4.EventManager)) { return this._EventManager_79; }
    if ((token === import4.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_80; }
    if ((token === import4.ɵDomRendererFactory2)) { return this._ɵDomRendererFactory2_81; }
    if ((token === import27.AnimationDriver)) { return this._AnimationDriver_82; }
    if ((token === import27.ɵAnimationStyleNormalizer)) { return this._ɵAnimationStyleNormalizer_83; }
    if ((token === import27.ɵAnimationEngine)) { return this._ɵAnimationEngine_84; }
    if ((token === import0.RendererFactory2)) { return this._RendererFactory2_85; }
    if ((token === import4.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_86; }
    if ((token === import0.Testability)) { return this._Testability_87; }
    if ((token === import4.Meta)) { return this._Meta_88; }
    if ((token === import4.Title)) { return this._Title_89; }
    if ((token === import28.InMemoryDbService)) { return this._InMemoryDbService_90; }
    if ((token === import28.InMemoryBackendConfig)) { return this._InMemoryBackendConfig_91; }
    if ((token === import5.XHRBackend)) { return this._XHRBackend_92; }
    if ((token === import5.RequestOptions)) { return this._RequestOptions_93; }
    if ((token === import5.Http)) { return this._Http_94; }
    if ((token === import5.BrowserXhr)) { return this._BrowserXhr_95; }
    if ((token === import5.ResponseOptions)) { return this._ResponseOptions_96; }
    if ((token === import5.XSRFStrategy)) { return this._XSRFStrategy_97; }
    if ((token === import6.ɵi)) { return this._ɵi_98; }
    if ((token === import6.FormBuilder)) { return this._FormBuilder_99; }
    if ((token === import9.Platform)) { return this._Platform_100; }
    if ((token === import9.ScrollDispatcher)) { return this._ScrollDispatcher_101; }
    if ((token === import9.ViewportRuler)) { return this._ViewportRuler_102; }
    if ((token === import9.OverlayContainer)) { return this._OverlayContainer_103; }
    if ((token === import9.ɵo)) { return this._ɵo_104; }
    if ((token === import9.Overlay)) { return this._Overlay_105; }
    if ((token === import9.FocusOriginMonitor)) { return this._FocusOriginMonitor_106; }
    if ((token === import9.UniqueSelectionDispatcher)) { return this._UniqueSelectionDispatcher_107; }
    if ((token === import9.InteractivityChecker)) { return this._InteractivityChecker_108; }
    if ((token === import9.FocusTrapFactory)) { return this._FocusTrapFactory_109; }
    if ((token === import9.LiveAnnouncer)) { return this._LiveAnnouncer_110; }
    if ((token === import9.MdDialog)) { return this._MdDialog_111; }
    if ((token === import9.MdDatepickerIntl)) { return this._MdDatepickerIntl_112; }
    if ((token === import9.MdIconRegistry)) { return this._MdIconRegistry_113; }
    if ((token === import9.MdSnackBar)) { return this._MdSnackBar_114; }
    if ((token === import9.ɵa)) { return this._ɵa_115; }
    if ((token === import29.BREAKPOINTS)) { return this._BREAKPOINTS_116; }
    if ((token === import13.BreakPointRegistry)) { return this._BreakPointRegistry_117; }
    if ((token === import14.MatchMedia)) { return this._MatchMedia_118; }
    if ((token === import22.MediaMonitor)) { return this._MediaMonitor_119; }
    if ((token === import24.ObservableMedia)) { return this._ObservableMedia_120; }
    if ((token === import3.ActivatedRoute)) { return this._ActivatedRoute_121; }
    if ((token === import3.NoPreloading)) { return this._NoPreloading_122; }
    if ((token === import3.PreloadingStrategy)) { return this._PreloadingStrategy_123; }
    if ((token === import3.RouterPreloader)) { return this._RouterPreloader_124; }
    if ((token === import3.PreloadAllModules)) { return this._PreloadAllModules_125; }
    if ((token === import3.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_126; }
    if ((token === import0.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_127; }
    if ((token === import15.ApiService)) { return this._ApiService_128; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_6.ngOnDestroy();
    (this.__ɵDomSharedStylesHost_80 && this._ɵDomSharedStylesHost_80.ngOnDestroy());
    (this.__RouterPreloader_124 && this._RouterPreloader_124.ngOnDestroy());
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory<any>(AppModuleInjector,import1.AppModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvYWJvdGV6L0Rlc2t0b3AvdGVzdDIvc3JjL2FwcC9hcHAubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL2Fib3Rlei9EZXNrdG9wL3Rlc3QyL3NyYy9hcHAvYXBwLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
