/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './about.component.scss.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../tabs/tabs.component.ngfactory';
import * as import3 from '../../../../../src/app/components/tabs/tabs.component';
import * as import4 from '../../../../../src/app/components/about/about.component';
const styles_AboutComponent:any[] = [import0.styles];
export const RenderType_AboutComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_AboutComponent,
  data: {}
}
);
export function View_AboutComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n  About Works!\n'])),
    (l()(),import1.ɵted((null as any),['\n'])),
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'my-tabs',([] as any[]),(null as any),(null as any),(null as any),import2.View_TabsComponent_0,import2.RenderType_TabsComponent)),
    import1.ɵdid(49152,(null as any),0,import3.TabsComponent,([] as any[]),(null as any),(null as any)),
    (l()(),import1.ɵted((null as any),['\n\n']))
  ]
  ,(null as any),(null as any));
}
function View_AboutComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'my-about',([] as any[]),(null as any),(null as any),(null as any),View_AboutComponent_0,RenderType_AboutComponent)),
    import1.ɵdid(114688,(null as any),0,import4.AboutComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const AboutComponentNgFactory:import1.ComponentFactory<import4.AboutComponent> = import1.ɵccf('my-about',import4.AboutComponent,View_AboutComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvYWJvdGV6L0Rlc2t0b3AvdGVzdDIvc3JjL2FwcC9jb21wb25lbnRzL2Fib3V0L2Fib3V0LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9hYm90ZXovRGVza3RvcC90ZXN0Mi9zcmMvYXBwL2NvbXBvbmVudHMvYWJvdXQvYWJvdXQuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvYWJvdGV6L0Rlc2t0b3AvdGVzdDIvc3JjL2FwcC9jb21wb25lbnRzL2Fib3V0L2Fib3V0LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvYWJvdGV6L0Rlc2t0b3AvdGVzdDIvc3JjL2FwcC9jb21wb25lbnRzL2Fib3V0L2Fib3V0LmNvbXBvbmVudC50cy5BYm91dENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxwPlxyXG4gIEFib3V0IFdvcmtzIVxyXG48L3A+XHJcbjxteS10YWJzPjwvbXktdGFicz5cclxuXHJcbiIsIjxteS1hYm91dD48L215LWFib3V0PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUFHO0lBRUM7SUFDSjtnQkFBQTtJQUFtQjs7Ozs7O0lDSG5CO2dCQUFBOzs7SUFBQTs7OyJ9
